service: synchrolife4biz-lp

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, self:custom.defaultStage}
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
        - "ses:SendRawEmail"
        - "ssm:GetParametersByPath"
      Resource:
        - "*"
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "ses:SendRawEmail"
        - "logs:PutLogEvents"
      Resource:
        - "arn:aws:logs:*:*:*"
        - "arn:aws:ses:us-east-1:*:identity/*"

custom:
  defaultStage: stg

functions:
  mail:
    handler: handler.handle
    events:
      - http:
          path: mail
          method: post
          cors: true
    timeout: 30
    memorySize: 256
    environment:
      STAGE: ${opt:stage, self:custom.defaultStage}